# Generated by Django 5.2.9 on 2025-12-22 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='points.point', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-created_at',),
            },
        ),
    ]
