# Generated by Django 5.2.9 on 2025-12-22 19:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название точки')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'точка',
                'verbose_name_plural': 'Точки',
            },
        ),
    ]
