# Generated by Django 5.2.9 on 2025-12-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_point_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название точки'),
        ),
    ]
